### ISSUE TITLE
Allow filenames for path parameter

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-loader#14]
Right now, the loader accepts only folder names for the "path" parameter. For a webdav folder with multiple zip files, it's useful to also support filenames.

For example: 

```
curl -d "share_url=https://uni-muenster.sciebo.de/index.php/s/G8vxQ1h50V4HpuA"  \
    -d "path=/metatainer.zip" \
     http://…/api/v1/compendium
```

**Comment by nuest** [comment]
And it would be good to make clear if that requires a leading `/` or not :-).

**Comment by LukasLohoff** [comment]
Specifying filenames works now, the file has to end in `.zip`, otherwise it can't be detected.

A leading slash is now added if necessary, so both options should work.

See https://github.com/o2r-project/o2r-loader/pull/42

**Comment by nuest** [comment]
Great. Please also create a PR for the API docs.
Will close this after merging the new code.
