### ISSUE TITLE
Make request timeout configurable

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-loader#19]
When uploading large files with the loader, the connection breaks because of the nginx and/or nodejs HTTP timeout after 60 or 120 seconds.

nodeJS HTTP:

https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_timeout

nginx (?):

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

**Comment by nuest** [comment]
I could replicate this using Chrome developer tools and "throttling" the network connection, using a large ZIP file (`bboxtainer.zip` with ~ 50 MB and "slow 3G" was large/slow enough).

The nginx log shows that "upstream timed out". However, the upload progress in the UI continues... but no log was triggered in loader at that point. The upload also continues in the background, but that is [another issue](https://github.com/o2r-project/o2r-platform/issues/82)

```
2017/08/30 14:06:13 [error] 7#7: *313 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /api/v1/compendium HTTP/1.1", upstream: "http://172.17.0.1:8088/api/v1/compendium", host: "localhost", referrer: "http://localhost/"
172.17.0.1 - - [30/Aug/2017:14:06:13 +0000] "POST /api/v1/compendium HTTP/1.1" 504 585 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.113 Chrome/60.0.3112.113 Safari/537.36"
172.17.0.1 - - [30/Aug/2017:14:06:14 +0000] "POST /api/v1/compendium HTTP/1.1" 408 0 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.113 Chrome/60.0.3112.113 Safari/537.36"
```

When setting the nginx timeout to `proxy_read_timeout 30m;`, the new error is

```
2017/08/30 15:34:18 [error] 9#9: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /api/v1/compendium HTTP/1.1", upstream: "http://172.17.0.1:8088/api/v1/compendium", host: "localhost", referrer: "http://localhost/"
```

Then increased the timeout for nodejs (see link above), also to 30 minutes.

_An upload that takes around 10 minutes works fine._

**Comment by nuest** [comment]
@LukasLohoff can you re-test with the changes I made in o2r-platform (https://github.com/o2r-project/o2r-platform/pull/83) and https://github.com/nuest/o2r-loader/commit/b90ca591f46530b69736a8bfa5eb4cadfd2410fe please?

**Comment by LukasLohoff** [comment]
done
