### ISSUE TITLE
specifiy if uploaded file is bag

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-loader#32]
To properly handle uploaded bags and workspaces, these have to be distinguishable. I propose to add an attribute `isBag` of type `boolean` to the ERC-metadata.

**Comment by nuest** [comment]
Depends on muncher `0.12.3`.

**Comment by nuest** [comment]
@jansule implementation ready for you!

**Comment by nuest** [comment]
Docs now online: http://o2r.info/o2r-web-api/compendium/metadata/#non-metadata-properties
