### ISSUE TITLE
Handling upload cancel

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-loader#37]
If a user cancels the upload of an ERC, the httpRequest will be aborted in the client. The loader should then remove the ERC. So far, the process stops, but the loader does no cleanup afterwards, so that existing files (e.g. uploaded archive) still exist.

See also [here](https://github.com/o2r-project/o2r-platform/issues/82)

**Comment by nuest** [comment]
@jansule Can you please re-check this? Thanks!

**Comment by nuest** [comment]
Works on my end, please close when you can confirm.
