### ISSUE TITLE
File upload with user level 0

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-loader#8]
It is possible to upload files even if the user level is 0.

**Comment by nuest** [comment]
@jansule Thanks for reporting this. Can you please clarify which version loader you are using? The image hash should be a start... or run `docker inspect o2r-loader`.

@LukasLohoff Can you have a look at this after Jan has answered?

**Comment by LukasLohoff** [comment]
@nuest I think I found the error: There is no `c.user.level.create_compendium` in config.js, only `c.user.level.load_webdav`.

It's fixed in this pull request: https://github.com/o2r-project/o2r-loader/pull/9

**Comment by jansule** [comment]
Pull request fixed the issue.
